### ISSUE TITLE
Kafka 1.0 download link does not work

### ISSUE THREAD

**Issue by spuder** [mthssdrbrg/kafka-cookbook#142]
The downloads for kafka 1.0 no longer includes the scala version as part of the url

Correct url

http://apache.mirrors.lucidnetworks.net/kafka/1.0.0/kafka-1.0.0-src.tgz

Url that cookbook tries (unsuccessfully) to use

https://archive.apache.org/dist/kafka/1.0.0/kafka_2.11-1.0.0.tgz

In test kitchen.yml

```yml
      kafka:
        version: "1.0.0"
        scala_version: "2.11"
        checksum: "d8edc001ea9ff1bcd27f8f196101b0dee326095dc9fb82c331a7f248abb6b5fb"
        md5_checksum: "760c15b192412ea4114368f6d6a391fa"
```

This is because the method `kafka_version_name` hard codes the scala_version as part of the url. 

https://github.com/mthssdrbrg/kafka-cookbook/blob/f5377155e00f54edb9217ff50f2f05c02e5dcd56/libraries/helpers.rb#L6-L8
