### ISSUE TITLE
Checksum fails

### ISSUE THREAD

**Issue by spuder** [mthssdrbrg/kafka-cookbook#74]
When running `kitchen create` the download will fail on the checksum verification step. 

I've verified that the checksum is correct by downloading from https://archive.apache.org/dist/kafka/0.8.1.1/kafka_2.9.2-0.8.1.1.tgz" and comparing the md5 and sha256 with the versions in the cookbook. 

MD5 (kafka_2.9.2-0.8.1.1.tgz) = 7541ed160f1b3aa1a5334d4e782ba4d3
cb141c1d50b1bd0d741d68e5e21c090341d961cd801e11e42fb693fa53e9aaed  kafka_2.9.2-0.8.1.1.tgz

For some reason, `Checksum on resource () does not match checksum on content (cb141c)` has an empty value inside the brackets. 

Is this a problem with the manifest? Or is a parameter missing on my part? I'm pretty new to chef. 

```chef
       ================================================================================
           Error executing action `create` on resource 'kafka_download[/tmp/kitchen/cache/kafka_2.9.2-0.8.1.1.tgz]'
           ================================================================================

       Chef::Exceptions::ChecksumMismatch
           ----------------------------------
           remote_file[/tmp/kitchen/cache/kafka_2.9.2-0.8.1.1.tgz] (/tmp/kitchen/cookbooks/kafka/providers/download.rb line 12) had an error: Chef::Exceptions::ChecksumMismatch: Checksum on resource () does not match checksum on content (cb141c)

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cookbooks/kafka/recipes/_install.rb

         6: kafka_download kafka_local_download_path do
             7:   source kafka_download_uri(kafka_tar_gz)
             8:   checksum node.kafka.checksum
             9:   md5_checksum node.kafka.md5_checksum
            10:   not_if { kafka_installed? }
            11: end
        12:

       Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cookbooks/kafka/recipes/_install.rb:6:in `from_file'

           kafka_download("/tmp/kitchen/cache/kafka_2.9.2-0.8.1.1.tgz") do
             action :create
             retries 0
         retry_delay 2
             default_guard_interpreter :default

             cookbook_name :kafka
             recipe_name "_install"
         source "https://archive.apache.org/dist/kafka/0.8.1.1/kafka_2.9.2-0.8.1.1.tgz"
         mode "644"
             not_if { #code block }
           end


       Running handlers:
       [2015-02-10T20:48:43+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-02-10T20:48:43+00:00] ERROR: Exception handlers complete
       [2015-02-10T20:48:43+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 1 resources updated in 65.305166066 seconds
       [2015-02-10T20:48:43+00:00] ERROR: kafka_download[/tmp/kitchen/cache/kafka_2.9.2-0.8.1.1.tgz] (kafka::_install line 6) had an error: Chef::Exceptions::ChecksumMismatch: remote_file[/tmp/kitchen/cache/kafka_2.9.2-0.8.1.1.tgz] (/tmp/kitchen/cookbooks/kafka/providers/download.rb line 12) had an error: Chef::Exceptions::ChecksumMismatch: Checksum on resource () does not match checksum on content (cb141c)
       [2015-02-10T20:48:43+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <init-style-upstart-ubuntu-1404>.
>>>>>> Please see .kitchen/logs/init-style-upstart-ubuntu-1404.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '
sudo -E /opt/chef/bin/chef-solo --config /tmp/kitchen/solo.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json
']
>>>>>> ----------------------
```

**Comment by spuder** [comment]
I think I figured it out. This is because kitchen is pulling from environment variables. How are you supposed to put the variables in into the environment with chef? 


```
suites:
  - name: init-style-upstart
    run_list:
      - recipe[java::default]
      - recipe[kafka::default]
    includes:
      - ubuntu-14.04
    attributes:
      kafka:
        init_style: 'upstart'
        version: <%= ENV.fetch('KAFKA_VERSION', '0.8.1.1') %>
        checksum: <%= ENV.fetch('KAFKA_CHECKSUM', '""') %>
        md5_checksum: <%= ENV.fetch('KAFKA_MD5', '""') %>
        ulimit_file: 128000
        broker:
          controlled_shutdown_enable: <%= ENV.fetch('KAFKA_CTRL_SHUTDOWN', nil) %>
          log_dirs: ['/mnt/kafka-logs-1', '/mnt/kafka-logs-2']
          zookeeper_connect: ['localhost:2181']
          zookeeper_connection_timeout_ms: 15_000
```
